Задача ColumnChart
js-tasks-ru/js-20200928_igor-kuzmin pull request #5
Opened 2020-10-15 06:21 UTC by I-g-o-r-K-u-z-m-i-n

2020-10-15 06:28 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
ColumnChart компонент
+ should be rendered correctly
+ should have ability to define label
+ should have ability to define link
+ should have ability to define total value
+ should have property 'chartHeight
+ should render data correctly
+ should have ability to be updated by new "data" values (should re-render only body with charts columns)
+ should have loading indication if data wasn't passed 
+ should have ability to be removed
```
```diff
NotificationMessage компонент
- should be rendered correctly
- should have ability to set duration
- should be removed after time defined in duration property
- should have ability to set message
- should have ability to set 'success' type of message
- should have ability to set 'error' type of message
- should have ability to define target element for rendering
- should have ability to be destroyed
```

2020-10-15 13:08 UTC, jsru commented
Пожалуйста, не меняйте «системные» файлы.
          Задача не может считаться решенной, если были изменены файлы тестов или другие «системные» файлы.
          Следующие файлы были изменены:
```diff
- package.json — изменен
```

2020-10-15 16:24 UTC, dosandk commented on package.json
> +  },
как эти изменения попали в PR?
ай-я-яй!

2020-10-15 16:24 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
>  export default class NotificationMessage {
не хвататет логики которая будет проверять наличие нотификейшена на странице и в случае если он присутствует - удалять его

2020-10-15 16:25 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +    if (this.data.length > 0) {
такие проверки лучше сокращать `if (this.data.length) ...`

2020-10-15 16:25 UTC, dosandk requested changes
необходимо поправить решение `NotificationMessage` и убрать изменения системных файлов

2020-10-18 23:00 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
SortableTable компонент - без обработчиков событий клика и динамической загрузки
+ should be rendered correctly
+ should not have default sorting
+ should sort "asc" correctly for "sortType" equal string
+ should sort "desc" correctly for "sortType" equal string
+ should sort "asc" correctly for "sortType" equal number
+ should sort "desc" correctly for "sortType" equal number
+ should have ability to be destroyed
```
```diff
ColumnChart компонент
+ should be rendered correctly
+ should have ability to define label
+ should have ability to define link
+ should have ability to define total value
+ should have property 'chartHeight
+ should render data correctly
+ should have ability to be updated by new "data" values (should re-render only body with charts columns)
+ should have loading indication if data wasn't passed 
+ should have ability to be removed
```
```diff
NotificationMessage компонент
+ should be rendered correctly
+ should have ability to set duration
+ should be removed after time defined in duration property
+ should have ability to set message
+ should have ability to set 'success' type of message
+ should have ability to set 'error' type of message
+ should have ability to define target element for rendering
+ should have ability to be destroyed
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2020-10-20 19:24 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +      NotificationMessage.oldElement.remove();
good 👍

2020-10-20 19:24 UTC, dosandk approved these changes

2020-10-20 19:25 UTC, merged